image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      
  - name: Run
    command: dotnet --version

vscode:
  extensions:
    - muhammad-sammy.csharp
