image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https
      dotnet Restore
      dotnet tool install --global dotnet-ef

      
  - name: Run
    command: export PATH="$PATH:/home/gitpod/.dotnet/tools"

vscode:
  extensions:
    - muhammad-sammy.csharp
